### PR TITLE
HttpWebResponse streams were not closed property, causing a full queue when making many requests

### PR DESCRIPTION
**Pull request by roelandhermans**
HttpWebRequest.GetResponse() returns a response that should be disposed after usage.
Not disposing the response causes all used sockets to stay in 'CLOSE_WAIT' state.
In our case we made +/- 100 calls per minute for 6 hours long, which resulted in an overflowing queue.

For questions: contact me at roeland@codevos.nl (mag in het Nederlands)

### CODE REVIEW

**Comment by LennardF1989** [comment]
Looks good to me on a first glance, nice job on the small refactor too, makes a lot more sense this way :) I'll pull this in, merge and update the NuGet package. Won't be before monday unfortunately, though!

**Comment by roelandhermans** [comment]
Nice! Thanks for the quick response and for adapting my changes.

**Comment by roelandhermans** [comment]
Hi Lennard,

Is there any news on when these changes will be merged into the master branch?

Regards,

Roeland

**Comment by jbreuer** [comment]
Any idea when this PR will be merged? We're currently running a custom build and we would like to use NuGet again.

**Comment by LennardF1989** [comment]
I'll squeeze in some time later today! :)

**Comment by jbreuer** [comment]
Do you think you can do it this week? We would like to go live next week with the NuGet version.

**Comment by LennardF1989** [comment]
@jbreuer @roelandhermans Merged and pushed to NuGet as v1.1.1!

**Pull request merged**
