### PR TITLE
Configurable

### PR DESCRIPTION
**Pull request by dnzbjorn**
I added the possibility to configure the accesstoken of Copernica, and the databaseid and the collectionid for models in a CopernicaNET configuration section.

### CODE REVIEW

**Comment by LennardF1989** [comment]
Thank you for your pull request! We'll do a peer review to make sure things still work properly and if so, obviously accept your pull!

Could you give a small example on the configuration section? We're still preparing some documentation and could include that as well :)

**Comment by dnzbjorn** [comment]
Hello Lennard,

The configuration section has the following structure:

<configSections>
      <section name="copernicanet"
type="Arlanet.CopernicaNET.Configuration.CopernicaSettings"/>
</configSections>
<copernicanet accesstoken="replacewithaccesstoken">
<models>
<model name="CopernicaLibraryImplementationExample.Models.Client"
databaseid="1"  /> 
<model name="CopernicaLibraryImplementationExample.Models.Product"
databaseid="1" collectionid="3" /> 
</models>
</copernicanet>

Vriendelijke groet / Best regards,

Björn Borneman
Software Engineer

**Comment by dnzbjorn** [comment]
Hello Lennard,

I was wondering when my pull request will be handled. I would like to use the requested functionality, and it would be best if the functionalitity is available in the NuGet package.

If you have any feedback, i would be happy to hear it from you.

**Comment by LennardF1989** [comment]
@dnzbjorn Sorry, I thought my collegue picked this up a few weeks ago already! It's technically his "baby" hence I left the ball with him. I'll pull his leg tomorrow, otherwise I'll do it myself.

**Comment by dnzbjorn** [comment]
Hello Ynze,

Is it possible update the CopernicaNET NuGet package to the newest version,
so we can use the NuGet package instead of the version found on GitHub?

Met vriendelijke groet,

Björn Borneman
Software Engineer

De Nieuwe Zaak http:/www.denieuwezaak.nl
Experts in e-commerce
Hanzeallee 28 / 8017 KZ / Zwolle

(T) 038 423 01 63

Altijd het laatste e-commerce nieuws in je inbox? Meld je aan voor de
wekelijkse nieuwsbrief! http://www.denieuwezaak.nl/ecommerce-nieuwsbrief/

Blijf ons volgen:

http://www.linkedin.com/companies/de-nieuwe-zaak
http://www.facebook.com/denieuwezaak
http://www.twitter.com/denieuwezaak
https://www.google.com/+denieuwezaak

2015-09-26 20:13 GMT+02:00 Ynze Nunnink notifications@github.com:

**Comment by ynzenu** [comment]
Hoi Björn,

The latest version is now available on nuget. Sorry for the late support on your great pull request. We've had alot of feedback but not much time to spend on updating. That's why we've decided to improve the library alot within the next month. The upcoming version will cause some breaking changes, so be sure to check out the breaking changes before updating in the near future. 

Thanks,

Ynze

**Pull request merged**
